# Site settings
title: "Holly's personal blog"
email: hwilliams@srk.com
description: My personal blog
url: "http://hwilliams10.github.io"

author:
  name      : 'Holly Williams'
  email     : hwilliams@srk.com
  facebook  : http://facebook.com/hrourke
  instagram : http://twitter.com/holly.rourke

github: https://github.com/hwilliams10

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
